[build]
  base = "moneyger.client"
  command = "npm run build -- --configuration=production"
  publish = "dist/moneyger.client/browser" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
